cp -vp doc/Makefile.in doc/Makefile.in.tmp  && sed -f ${SED_MK} doc/Makefile.in.tmp > doc/Makefile.in
cp -vp info/Makefile.in info/Makefile.in.tmp  && sed -f ${SED_MK} info/Makefile.in.tmp > info/Makefile.in
cp -vp intl/Makefile.in intl/Makefile.in.tmp  && sed -f ${SED_MK} intl/Makefile.in.tmp > intl/Makefile.in
cp -vp lib/Makefile.in lib/Makefile.in.tmp  && sed -f ${SED_MK} lib/Makefile.in.tmp > lib/Makefile.in
cp -vp m4/Makefile.in m4/Makefile.in.tmp  && sed -f ${SED_MK} m4/Makefile.in.tmp > m4/Makefile.in
cp -vp Makefile.in Makefile.in.tmp  && sed -f ${SED_MK} Makefile.in.tmp > Makefile.in
cp -vp makeinfo/Makefile.in makeinfo/Makefile.in.tmp  && sed -f ${SED_MK} makeinfo/Makefile.in.tmp > makeinfo/Makefile.in
cp -vp makeinfo/tests/Makefile.in makeinfo/tests/Makefile.in.tmp  && sed -f ${SED_MK} makeinfo/tests/Makefile.in.tmp > makeinfo/tests/Makefile.in
cp -vp util/Makefile.in util/Makefile.in.tmp  && sed -f ${SED_MK} util/Makefile.in.tmp > util/Makefile.in
cp -vp doc/Makefile.in doc/Makefile.in.tmp && sed -f ${SED_MK1} doc/Makefile.in.tmp > doc/Makefile.in
cp -vp info/Makefile.in info/Makefile.in.tmp && sed -f ${SED_MK1} info/Makefile.in.tmp > info/Makefile.in
cp -vp intl/Makefile.in intl/Makefile.in.tmp && sed -f ${SED_MK1} intl/Makefile.in.tmp > intl/Makefile.in
cp -vp lib/Makefile.in lib/Makefile.in.tmp && sed -f ${SED_MK1} lib/Makefile.in.tmp > lib/Makefile.in
cp -vp m4/Makefile.in m4/Makefile.in.tmp && sed -f ${SED_MK1} m4/Makefile.in.tmp > m4/Makefile.in
cp -vp Makefile.in Makefile.in.tmp && sed -f ${SED_MK1} Makefile.in.tmp > Makefile.in
cp -vp makeinfo/Makefile.in makeinfo/Makefile.in.tmp && sed -f ${SED_MK1} makeinfo/Makefile.in.tmp > makeinfo/Makefile.in
cp -vp makeinfo/tests/Makefile.in makeinfo/tests/Makefile.in.tmp && sed -f ${SED_MK1} makeinfo/tests/Makefile.in.tmp > makeinfo/tests/Makefile.in
cp -vp util/Makefile.in util/Makefile.in.tmp && sed -f ${SED_MK1} util/Makefile.in.tmp > util/Makefile.in
cp -vp po/Makefile.in.in po/Makefile.in.in.tmp && sed -f ${SED_PO_MK} po/Makefile.in.in.tmp > po/Makefile.in.in
